# vim:ft=ansible:
---

- name: Check if inside AWS.
  uri:
    url: http://169.254.169.254/latest/meta-data
    timeout: 2
  register: aws_uri_check
  ignore_errors: yes

- set_fact:
    is_aws_environment: "{{ aws_uri_check.status == 200 }}"

- name: Get ec2 metadata
  ec2_metadata_facts:
  when: is_aws_environment
